### PR TITLE
Fixes kamermans/guzzle-oauth2-subscriber#43

### PR DESCRIPTION
**Pull request by cyberwolf**

### CODE REVIEW

**Comment by hvanoch** [comment]
This would be convenient...

**Review by kamermans — APPROVED** [review]

**Comment by kamermans** [comment]
Sorry I missed this PR, it came just days before a major life emergency and I totally forgot about it!

**Comment by hvanoch** [comment]
@kamermans thanks for the quick response now.

Could you also create a new tag for this? That way we can use right away.

**Comment by cyberwolf** [comment]
No problem @kamermans, happy I've been able to contribute some small bits.

**Comment by kamermans** [comment]
Sure, I just need to check a few more PRs and then I'll release it shortly!

**Comment by kamermans** [comment]
Thanks @cyberwolf!

Here's the release: https://github.com/kamermans/guzzle-oauth2-subscriber/releases/tag/v1.0.12

**Comment by hvanoch** [comment]
@kamermans Thank you very much  :heart:

**Pull request merged**
